db_path: /home/users/t/trickovi/scratch/sourmash/sourmash-hash-manipulation-21/51_100_union/output/specific_hashomes.sbt.zip
sample_table: /home/users/t/trickovi/shared_scratch/datasets/CAMI/new_posthumgut/samples.tsv
trim_reads: False


kmer_len: 51
scaled: 1000
scaled_downsample: 1000
threshold_bp: 15000


#RESOURCES
tmp_dir: /scratch
mem_mb: 24000
time_min: 120
threads: 1
